import type { Metadata } from "next";
import { Manrope, Roboto, Roboto_Flex } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const manrope = Manrope({
  subsets: ["cyrillic"],
  weight: ["400", "600", "700"],
  variable: "--font-manrope",
});
const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});
const robotoFlex = Roboto_Flex({
  subsets: ["cyrillic"],
  weight: ["400", "500", "600"],
  variable: "--font-roboto-flex",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua">
      <body
        className={`${manrope.variable} ${roboto.variable} ${robotoFlex.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
